Upgrade to EasyMock 5.4.0
This resolves a JDK 21 compatibility issue:

java.lang.IllegalArgumentException: Could not create type
...
Caused by: java.lang.IllegalArgumentException: org.jclouds.blobstore.strategy.internal.DeleteAllKeysInList$$$EasyMock$6 must be defined in the same package as org.easymock.internal.ClassProxyFactory